[package]
name = "calibrate"
version = "1.0.0"
edition = "2024"
authors = ["ekahPruthvi <ekahpdp@gmail.com>"]
description = "cynageos settings"

[dependencies]
dbus = "0.9.7"
gtk4 = "0.9.6"
networkmanager = "0.5.0"
vte4 = "0.8.0"
